### ISSUE TITLE
Add example with colored text for highlighting mentions

### ISSUE THREAD

**Issue by cferrios** [signavio/react-mentions#184]
Would be nice to have an alternate highlight style where the text color would be colored instead of the background

**Comment by saidymadi** [comment]
this was fairly more complex than I would have liked it. 

basically you need to give the textarea component a z-index style of 0 
and gice the highlighter component a z-index of 999 

This is basically to put the highlight on top of the textarea

then modify defaulthighlightstyle to use color instead of background

**Comment by jfschwarz** [comment]
@saidymadi's approach seems like your best option. Depending on text aliasing in different OS and browsers, overlaying the visible text of the textarea with colored text for the mentions might look awkward, though. Try for yourself.

I cannot come up with a better solution. Assigning `color: transparent` as a style to the `textearea` also is no option since this would mean that users won't see the caret anymore. If anyone has a creative idea for this, let us know.

**Comment by alexandernanberg** [comment]
@jfschwarz This feature would be a really good addition. Tried with the z-index hack but it looked a bit awkward. Haven't figured out any other solution for this either, other than converting the `textarea` to a `div` with `contenteditable`. But that would probably mean a large rewrite of the plugin.

Would be nice to see this feature being added to the a roadmap for the next major release

**Comment by jfschwarz** [comment]
Adding `background-color: white` to the highlight style (in combination with the z-index trick described above) might improve the result. We should add an example for this.

**Comment by srjkrl20011991** [comment]
@jfschwarz  Please add atleast one example and let us know. This hack is not working for me

**Comment by brianarpie** [comment]
I found a simple solution for this that works for me. 

I'm using CSS modules, which isn't important, but here's the basic shape of my solution:

Component
```
<Mention className={classNames.mentions__mention} {...props} />
```

CSS
```
.mentions__mention {
  color: $light-blue;
  z-index: 1;
  position: relative;
}
```

Hopefully, this is helpful to others.

**Comment by robbiegprocore** [comment]
The z-index hack works, but then the cursor is gone and nothing the text area does not work. 🤔

**Comment by robbiegprocore** [comment]
After trying what I believe to be every option, **the text of a selected mention HAS to be same color as the rest of the text in the text area**

**Comment by YasirAtMatlab** [comment]
CSS 
```
.mentions__mention {
  color: #005895;
  z-index: 1;
  position: relative;
  mix-blend-mode: color;
}

```
Using mix-blend-mode works and doesn't hide the cursor also.
