### ISSUE TITLE
Add support for custom regex

### ISSUE THREAD

**Issue by jfschwarz** [signavio/react-mentions#21]
The regex generically derived from the markup is sometimes not right. E.g. for markup `@__id__` and value "@johndoe " it would only match "@j". In such situations, the user should be able to provide a customized regex, such as `/@(\w+)/g`.

**Comment by jfschwarz** [comment]
As JavaScript does not support lookbehind, we probably also need to support customizing the replace function for markup matches.

This would enable users to use, for instance, a regex like this `/(^|\s)@(\w+)($|\s)/g` and replace matches with `$1$2$3`, effectively only stripping out the `@`.

**Comment by nassimbenkirane** [comment]
Hi @jfschwarz !

Thanks for your work :) This repo is really cool.

At Zenchef we wanted our markup to be `:__id__`, so we ended up forking this project.
I made some changes, copying the work that was previously done with your custom-regex branch.

The tests about id, display, and type positions don't pass, but that makes sense since I did applied the same changes it as you did here : https://github.com/signavio/react-mentions/commit/3a7d7d1af407cf57c91e6a3605c82b3876dcddb4#diff-cf3a264059d2124ecf13cd8a659e780dR812

The code is at https://github.com/zenchef/react-mentions/tree/feature/custom-regex, do you want me to create a PR ?

Thanks

**Comment by jfschwarz** [comment]
I was quite busy during the last days, but today finally got around looking at you branch. It would be cool to support custom regex, so thanks for picking up the work on this feature. 👌 It would be great if you could submit a PR!

**Comment by activescott** [comment]
I want to support @email@domain.tld (similar to google mentions) and this fix for custom regex would help here too.

**Comment by nassimbenkirane** [comment]
Hey,
I was a little busy lately but I will try to provide a PR today :)

Hopefully it should work for @email@domain.tld
