### ISSUE TITLE
Any way to specify a container for the mentions to appear in?

### ISSUE THREAD

**Issue by homerlex** [signavio/react-mentions#226]
Instead of following the cursor we'd like the mentions list to appear in a given div. Is there any way to do this?

**Comment by jfschwarz** [comment]
There's currently no way to specify a container element for the suggestions overlay. However, you can override the suggestion elements style attributes, which allows you to place it at a fixed position instead of following the cursor.

To override the suggestions element's style via inline styles, pass a `style` prop to `MentionsInput`:

```javascript
<MentionsInput
  style={{
    suggestions: {
      top: 'auto',
      left: 'auto',
    }
  }}
/>
```

You can also override styles via css, if you prefer that, by assigning a `className` prop. Make sure to add an `!important` flag to your css style definitions if you need to override the default inline styles.
