### ISSUE TITLE
Support dynamic markup depending on type

### ISSUE THREAD

**Issue by delgermurun** [signavio/react-mentions#264]
Hello,
Thank you for great package. It helps a lot.

I need to create different markups depending on type. As far as I know, `markup` prop only accepts "string", so I couldn't make it.

Can we change `markup` to accept `string` or `function`?
same function that `displayTransform` receives (`function (id, display, type)`).

Thanks.

**Comment by jfschwarz** [comment]
Since we've merged https://github.com/signavio/react-mentions/pull/255, theoretically it would be possible to add support for `markup`. In that case, the user would have to provide a custom `regex` prop, because it is impossible for us to automatically derive a regex from dynamic markup.

To convince us that this feature is useful, could you please describe, maybe using an example illustrating your use case, why you need a function for `markup`?

**Comment by delgermurun** [comment]
@jfschwarz thank you for your response.

Let me try to explain my situation.

We have 2 different mentions one for members, other one is for mentioning discussion (some kind of link). So I need to render `@display` for members and `[display](id)` for discussions (btw: we use markdown for formatting).

For discussions I used `id` field for `url`, `display` is title of discussion.
Please ask me, if something is not clear.

Thanks.

**Comment by jfschwarz** [comment]
You could achieve the same by mapping the `value` prop before passing it to `<MentionsInput/>`, replacing `@<username>` with `@[<username>](member:<username>)` and `[<title>](<id>)` with `@[<title>](discussion:<id>)`. Then in the `onChange` handler you have to apply the reverse mapping.

That being said, we would still accept a PR for this to make this scenario a bit more ergonomic.

**Comment by delgermurun** [comment]
@jfschwarz Great. I'll let you know after I tried it.

I am happy to work on PR. Let's discuss about specifics later.
Thank you.

**Comment by delgermurun** [comment]
fix by #300. Thanks!
