### ISSUE TITLE
Longer list of mentions is not visible below the viewport

### ISSUE THREAD

**Issue by dep** [signavio/react-mentions#336]
**Steps to reproduce:**

1. Navigate to a mention where the input is at the bottom of the viewport
2. Start typing a mention
3. Notice the suggestion box appears below the viewport and is not viewable
4. Using the up/down arrow, it's impossible to know which mention you are selecting

**Expected behaviour:**
1. Opening the mention suggestion box at the bottom of the viewport should scroll it in to view.
2. Arrowing down on suggestions should also scroll the viewport so the user can see which suggestions the keyboard is exposing.

**Observed behaviour:**

![](https://dpeck.d.pr/bVqOOj+)

**Workaround:**
Manually scroll the viewport down.

**Comment by kashifshamaz21** [comment]
@jfschwarz For this issue, maybe we should think of adding some logic to render the suggestions list "upwards" after the trigger text character is input by user. Many of the tooltip components do this to handle the "less available real estate" scenario.. I'll see if i can put some time on working on this issue. Will keep this thread posted if i get something to work!

**Comment by kashifshamaz21** [comment]
@jfschwarz I started working on a PR for fixing this issue, and have gotten it working, that's when i stumbled upon another PR (#339) which has already fixed this issue  and that PR seems pretty close to getting merged. So I won't spend more time on this issue, hoping the 339 goes through.
Also, this issue seems to be duplicate for #269 
Would be good to close this and track the fix and other discussions on this issue on the PR.
