### ISSUE TITLE
Why not at the bottom of the input box

### ISSUE THREAD

**Issue by JoyNop** [signavio/react-mentions#365]
**Steps to reproduce:**

1. Enter the first line....
2. Enter the second line.....

Enter more and more content

**Expected behaviour:**
The last line should be at the bottom of the input box.
**Observed behaviour:**
Why not at the bottom of the input box
**Workaround:**
I need help

Chrome and firefox can't browse normally

`package: "react-mentions": "^3.3.0",`

![bug3.gif](https://i.loli.net/2019/10/16/RCsZyD9Pn5oBpj2.gif)

**Comment by jfschwarz** [comment]
This looks like the text styles of the textarea and the highlighting div are different. It's crucial that all css properties, such as `font-size`, `line-height` absolutely match in these two elements, so that the highlights are positioned correctly. Use dev tools to identify how to adjust your styles.
