### ISSUE TITLE
Square brackets in the display field breaks the editor

### ISSUE THREAD

**Issue by gdoenlen** [signavio/react-mentions#382]
**Steps to reproduce:**

1. Add a suggestion with display: `Hello [Test]` and id: 1
2. Try to mention that object.
3. The editor fails to see it as a mention and displays: `@[Hello [Test]](1)`

**Expected behaviour:**
The editor should see it as a mention and highlight and only show `Hello [Test]`

**Observed behaviour:**
The editor fails to see it as a mention and displays: `@[Hello [Test]](1)`

![image](https://user-images.githubusercontent.com/17297466/74866292-a45f7680-5320-11ea-857c-4993874e4f09.png)

**Comment by jfschwarz** [comment]
You might want to define custom values for the `markup`, `displayTransform`, and `regex` props of the `<Mention />` element (see: https://github.com/signavio/react-mentions#configuration). This way you can either use a markup without square brackets or you could try to escape the square brackets in the display values, use a compatible regular expression, and unescape in `transformDisplay`.

**Comment by gdoenlen** [comment]
It happens with any markup., not just square brackets. I can reproduce with `markup="@!__display__!(__id__)"` and `markup="@!BLAH__display__BLAH!(__id__)"`

Escaping regex key characters in the display strings doesn't work either.

**Comment by jfschwarz** [comment]
Hmm, I see no reason why it should not work for `markup="@!__display__!(__id__)"`. The second markup would require you to define a custom `regex`. This is because we're making some assumptions when deriving the regex automatically from the patterns. Look at https://github.com/signavio/react-mentions/blob/master/src/utils/markupToRegex.js to understand more.

So you might want to try defining a custom `regex`. Otherwise, feel free to prepare a repro on jsfiddle or similar, so we can take a look.
