### ISSUE TITLE
displayTransform is not working properly with multiple Mention component

### ISSUE THREAD

**Issue by Sandx3** [signavio/react-mentions#384]
**Steps to reproduce:**

1. Add two **Mention** components inside **MentionsInput**
2. Pass props to **first Mention**:
`
     <Mention
          trigger='@'
          data={fetchData}
          displayTransform={(id, label) => `@${label}`}
          appendSpaceOnAdd
        />
`

3. Pass props to **second Mention**:
`
     <Mention
          trigger='#'
          data={fetchTags}
          displayTransform={(id, label) => `#${label}`}
          appendSpaceOnAdd
        />
`

4.  Then in the app select some @user and #tag

**Expected behaviour:**
Inside input selected user should be predefined with '@' and selected tag should be predefined with '#'

**Observed behaviour:**
Inside input selected user is predefined with '@' and selected tag is predefined also with '@'
It seems that it is using the first defined **displayTransform**, because after changing the order of the Mentions, all are getting predefined with '#'.

**Workaround:**
Don't use **displayTransform** to add predefined character, and add the predefined character in the mention suggestions as a display value. 

**Why it is a problem?**
First of all it is confusing for the user, because he don't get what he has written. Second of all, since there is no **onRemove** event on Mention component, I'm using the mentions argument in **onChange** of the MentionsInput. And inside the selected mentions, all of them are in one array, with the same predefined character, so I don't know on what basis I should distinguish them and send the relevant data to the database.

- Is there any way to fix this **displayTransform** issue?
- And by the way, can you add **onRemove** event support for the Mention component?

**Comment by jfschwarz** [comment]
> Is there any way to fix this displayTransform issue?

The problem you are seeing is happening because all the mentions are identified as user mentions. Since you are using the default markup (`@[__display__](__id__)`) for both `<Mention>` sources it will start parsing the `value` prop for the first source first and identify all mentions to be users. Then it looks at the second `<Mention>` source for tags, but then there are not mentions left.

You must define a unique pattern for each `<Mention>` element, e.g.:

```
<Mention trigger='@' markup={`@[__display__](__id__)`} data={fetchData} displayTransform={(id, label) =>@${label}} appendSpaceOnAdd />
<Mention trigger='#' markup={`#[__display__](__id__)`} data={fetchTags} displayTransform={(id, label) =>#${label}} appendSpaceOnAdd />
```

> And by the way, can you add onRemove event support for the Mention component?

We are not planning to do that. See https://github.com/signavio/react-mentions/pull/288#issuecomment-496870103
