### ISSUE TITLE
Adding support for multiple triggers afterwards

### ISSUE THREAD

**Issue by obaid** [signavio/react-mentions#397]
This is more of a question than a bug:

I have a project where we were using this library to handle tags input. Now we are looking for a way to add support for other triggers like `@` to insert mentions. However, when I add another trigger following the example provided, it is looking for `type` on the previous ones as well.

Is there a way to nicely upgrade all the existing ones?

**Comment by jfschwarz** [comment]
Since v3 the type property of mentioned items no longer exists. Instead each mentioning type defines a trigger and a specific pattern. See: https://github.com/signavio/react-mentions/blob/master/demo/src/examples/MultipleTrigger.js

So I suggest upgrading react-mentions in your project. (v3 breaking changes are documented here: https://github.com/signavio/react-mentions/releases/tag/v3.0.0)
