### ISSUE TITLE
Styles and classname on multiple triggers are ignored

### ISSUE THREAD

**Issue by CorfitzMe** [signavio/react-mentions#405]
**Steps to reproduce:**
Check out codesandbox: https://codesandbox.io/s/react-mentions-bugfixing-kn0iy
If you type in `:` or `/` to trigger either list, it always return the green colour in highlighter, and only apply the first classname declared in `Mention` triggers.

**Expected behaviour:**
Having assigned a classname per `Mention` Trigger, I expected that the class would be applied in the highlighter accordingly depending on which Trigger was used..

**Observed behaviour:**
The first `Mention` Trigger child in `MentionsInput` component overrules with its classname prop and style prop. (The codesandbox currently only uses a classname prop, but style has been tested as well.)

If you change the browser inspect tool and find the highlihgter, you'll see that only the first declared trigger classname is used.

**Workaround:**
Hmm... Have been looking for one... I just downloaded the latest 4.0.0 version and have tried falling back to 3.3.0 to see if that solved anything, but apparently not.

**Comment by jfschwarz** [comment]
The problem exists because both `<Mentions>` sources use the same markup pattern (the default one) so that there is no way for react-mentions to know which mention is associated to which source. react-mentions just uses the first matching pattern.

To fix the problem just assign distinct `markup` props to both `<Mention>` elements: https://codesandbox.io/s/react-mentions-bugfixing-77f2d?file=/src/App.tsx

It would make sense to use the specified `trigger` value to build the default markup to simplify this. I've captured it as an idea: https://github.com/signavio/react-mentions/issues/406

**Comment by CorfitzMe** [comment]
Brilliant... I actually wasn't aware of the markup attribute.. It was my assumption, that as long as I didn't touch anything, "default" behaviour would have kicked in :D Which it also did apparently.. Thanks a lot! Cheers!
