### ISSUE TITLE
Multiline textarea and scrolling

### ISSUE THREAD

**Issue by yjaspar** [signavio/react-mentions#539]
**Steps to reproduce:**

1. Add overflow-y to `*__input`
2. Checkout the chrome inspector and witness that:
![image](https://user-images.githubusercontent.com/1977547/148053879-df784474-1525-4537-bce1-5861854c1c51.png)

- The border shows great
- The `overflow-y` does not, because it seems that at the element level (textarea) there is an `overflow: hidden` that overwrites it.

**Expected behaviour:**
- Overflow can be overwritten by modular CSS

**Comment by jfschwarz** [comment]
Setting overflow on the input element is not the right approach, since this would mean that the text scrolls, but the mention highlights behind it won't.

Check the scrollable example to see how to do this the right way: https://github.com/signavio/react-mentions/blob/master/demo/src/examples/Scrollable.js

**Comment by jfschwarz** [comment]
You can only override default inline styles using `overflow-y: auto !important`
